# render.yaml (at the root of your project)
services:
  - type: web
    name: softaka
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn filecr_clone.wsgi:application"
    healthCheckPath: /admin/login/ # Or your preferred health check path
    envVars:
      - key: SECRET_KEY
      - key: DATABASE_URL
      - key: ALLOWED_HOSTS
    # NEW: Add 'python manage.py compress' to the releaseCommand
    releaseCommand: "python manage.py collectstatic --noinput && python manage.py compress --force && python manage.py migrate"
    # Added '--force' to compress, as sometimes it skips if it thinks files are up to date.
