# Generated by Django 4.2.22 on 2025-06-25 15:25

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='software',
            options={'ordering': ['name'], 'verbose_name_plural': 'Software'},
        ),
        migrations.RemoveField(
            model_name='software',
            name='download_count',
        ),
        migrations.RemoveField(
            model_name='software',
            name='installation_guide',
        ),
        migrations.RemoveField(
            model_name='software',
            name='screenshots',
        ),
        migrations.AlterField(
            model_name='downloadlink',
            name='name',
            field=models.CharField(help_text="e.g., '64-bit Installer', 'Portable Version'", max_length=100),
        ),
        migrations.AlterField(
            model_name='downloadlink',
            name='url',
            field=models.URLField(help_text='The actual download URL.', max_length=500),
        ),
        migrations.AlterField(
            model_name='software',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Full description of the software.', null=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='file_size',
            field=models.CharField(blank=True, help_text="Overall file size (e.g., '1.2 GB').", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='homepage_description',
            field=models.TextField(blank=True, help_text="A short description for the software's homepage/detail page (max 300 characters recommended).", max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='software_images/'),
        ),
        migrations.AlterField(
            model_name='software',
            name='license_type',
            field=models.CharField(choices=[('Free', 'Free'), ('Freemium', 'Freemium'), ('Trial', 'Trial'), ('Paid', 'Paid'), ('Open Source', 'Open Source')], default='Free', max_length=50),
        ),
        migrations.AlterField(
            model_name='software',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='operating_system',
            field=models.CharField(choices=[('Windows', 'Windows'), ('macOS', 'macOS'), ('Linux', 'Linux'), ('Android', 'Android'), ('iOS', 'iOS'), ('Cross-Platform', 'Cross-Platform')], default='Windows', max_length=50),
        ),
        migrations.AlterField(
            model_name='software',
            name='requirements',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='System requirements for the software.', null=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='website_link',
            field=models.URLField(blank=True, help_text='Official website link.', null=True),
        ),
        migrations.AlterField(
            model_name='softwaredownloadpageversion',
            name='additional_info',
            field=models.TextField(blank=True, help_text='Any additional notes specific to this download page version.', null=True),
        ),
        migrations.AlterField(
            model_name='softwaredownloadpageversion',
            name='display_title',
            field=models.CharField(blank=True, help_text="A specific title for this download page version (e.g., 'Latest 2025 Release').", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='softwaredownloadpageversion',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='softwaredownloadpageversion',
            name='version_number',
            field=models.CharField(help_text='e.g., 1.0, 2.5.1 (specific to this download page)', max_length=50),
        ),
        migrations.AlterField(
            model_name='softwareversion',
            name='additional_info',
            field=models.TextField(blank=True, help_text='Any additional notes about this version.', null=True),
        ),
        migrations.AlterField(
            model_name='softwareversion',
            name='download_link_url',
            field=models.URLField(blank=True, help_text='Direct download URL for this version (if primary).', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='softwareversion',
            name='is_current_version',
            field=models.BooleanField(default=False, help_text='Set as current version for this software.'),
        ),
        migrations.AlterField(
            model_name='softwareversion',
            name='version_number',
            field=models.CharField(help_text='e.g., 1.0, 2.5.1', max_length=50),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the commenter.', max_length=80)),
                ('email', models.EmailField(blank=True, help_text='Email of the commenter (optional).', max_length=254, null=True)),
                ('content', models.TextField(help_text='The comment text.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_comment', models.BooleanField(default=False, help_text='Only approved comments will be displayed.')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='software.software')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['created_at'],
            },
        ),
    ]
