# Generated by Django 5.1.7 on 2025-06-25 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0002_alter_software_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='average_rating',
            field=models.FloatField(default=0.0, help_text='Calculated average rating of the software.'),
        ),
        migrations.AddField(
            model_name='software',
            name='total_ratings',
            field=models.IntegerField(default=0, help_text='Total number of ratings received.'),
        ),
        migrations.AlterField(
            model_name='downloadpagespecificlink',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order in which these links are displayed.'),
        ),
    ]
