# Generated by Django 5.1.7 on 2025-06-26 00:17

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0005_alter_rating_unique_together_rating_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='downloadlink',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='softwaredownloadpageversion',
            options={'ordering': ['-release_date', '-version_number'], 'verbose_name': 'Software Download Page Version', 'verbose_name_plural': 'Software Download Page Versions'},
        ),
        migrations.AlterModelOptions(
            name='softwareversion',
            options={'ordering': ['-release_date', '-version_number']},
        ),
        migrations.AlterUniqueTogether(
            name='downloadlink',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='softwaredownloadpageversion',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='softwareversion',
            name='additional_info',
        ),
        migrations.AddField(
            model_name='softwaredownloadpageversion',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Full description for this specific download page.', null=True),
        ),
        migrations.AlterField(
            model_name='downloadlink',
            name='name',
            field=models.CharField(help_text="e.g., 'Mirror 1', 'Google Drive Link'", max_length=100),
        ),
        migrations.AlterField(
            model_name='downloadlink',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='downloadlink',
            name='url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='downloadpagespecificlink',
            name='name',
            field=models.CharField(help_text="Name of the download link (e.g., 'Direct Download', 'Mirror 1').", max_length=100),
        ),
        migrations.AlterField(
            model_name='downloadpagespecificlink',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order in which these links are displayed on the download page.'),
        ),
        migrations.AlterField(
            model_name='downloadpagespecificlink',
            name='url',
            field=models.URLField(help_text='The URL for this specific download.', max_length=500),
        ),
        migrations.AlterField(
            model_name='downloadpagespecificlink',
            name='version_for_page',
            field=models.ForeignKey(help_text='The specific download page version this link belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='specific_download_links', to='software.softwaredownloadpageversion'),
        ),
        migrations.AlterField(
            model_name='software',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='software',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='software_list', to='software.category'),
        ),
        migrations.AlterField(
            model_name='software',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='file_size',
            field=models.CharField(blank=True, help_text="e.g., '150 MB', '2.3 GB'", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='homepage_description',
            field=models.TextField(blank=True, help_text="A short description for the homepage. If left blank, 'description' will be used.", null=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='license_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='operating_system',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='total_ratings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='software',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='website_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='softwaredownloadpageversion',
            name='display_title',
            field=models.CharField(default='', help_text="Title for the download page (e.g., 'Microsoft Office 2021 Pro Plus Download').", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='softwaredownloadpageversion',
            name='software',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_pages', to='software.software'),
        ),
        migrations.AlterField(
            model_name='softwaredownloadpageversion',
            name='version_number',
            field=models.CharField(help_text='Version number associated with this download page.', max_length=50),
        ),
        migrations.AlterField(
            model_name='softwareversion',
            name='download_link_url',
            field=models.URLField(blank=True, help_text='Direct download link for this version (optional).', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='softwareversion',
            name='is_current_version',
            field=models.BooleanField(default=False, help_text='Mark as the current/latest version for this software.'),
        ),
        migrations.AlterField(
            model_name='softwareversion',
            name='version_number',
            field=models.CharField(max_length=50),
        ),
    ]
