# Generated by Django 5.1.7 on 2025-06-26 00:24

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0006_alter_downloadlink_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='downloadlink',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Download Link', 'verbose_name_plural': 'Download Links'},
        ),
        migrations.AlterModelOptions(
            name='softwaredownloadpageversion',
            options={'ordering': ['-release_date', '-version_number'], 'verbose_name': 'Download Page Version', 'verbose_name_plural': 'Download Page Versions'},
        ),
        migrations.AlterModelOptions(
            name='softwareversion',
            options={'ordering': ['-release_date', '-version_number'], 'verbose_name': 'Software Version', 'verbose_name_plural': 'Software Versions'},
        ),
        migrations.RemoveField(
            model_name='software',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='software',
            name='total_ratings',
        ),
        migrations.RemoveField(
            model_name='softwaredownloadpageversion',
            name='description',
        ),
        migrations.AddField(
            model_name='softwaredownloadpageversion',
            name='additional_info',
            field=models.TextField(blank=True, help_text='Any additional notes specific to this download page version.', null=True),
        ),
        migrations.AddField(
            model_name='softwareversion',
            name='additional_info',
            field=models.TextField(blank=True, help_text='Any additional notes about this version.', null=True),
        ),
        migrations.AlterField(
            model_name='downloadlink',
            name='name',
            field=models.CharField(help_text="e.g., '64-bit Installer', 'Portable Version'", max_length=100),
        ),
        migrations.AlterField(
            model_name='downloadlink',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order in which links are displayed.'),
        ),
        migrations.AlterField(
            model_name='downloadlink',
            name='url',
            field=models.URLField(help_text='The actual download URL.', max_length=500),
        ),
        migrations.AlterField(
            model_name='downloadpagespecificlink',
            name='name',
            field=models.CharField(help_text="Title for the download link (e.g., '64-bit Installer', 'Portable Version').", max_length=100),
        ),
        migrations.AlterField(
            model_name='downloadpagespecificlink',
            name='url',
            field=models.URLField(help_text='The actual URL for this specific download.', max_length=500),
        ),
        migrations.AlterField(
            model_name='downloadpagespecificlink',
            name='version_for_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specific_download_links', to='software.softwaredownloadpageversion'),
        ),
        migrations.AlterField(
            model_name='software',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='software_items', to='software.category'),
        ),
        migrations.AlterField(
            model_name='software',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Full description of the software.', null=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='file_size',
            field=models.CharField(blank=True, help_text="Overall file size (e.g., '1.2 GB').", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='homepage_description',
            field=models.TextField(blank=True, help_text="A short description for the software's homepage/detail page (max 300 characters recommended).", max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='license_type',
            field=models.CharField(choices=[('Free', 'Free'), ('Freemium', 'Freemium'), ('Trial', 'Trial'), ('Paid', 'Paid'), ('Open Source', 'Open Source')], default='Free', max_length=50),
        ),
        migrations.AlterField(
            model_name='software',
            name='operating_system',
            field=models.CharField(choices=[('Windows', 'Windows'), ('macOS', 'macOS'), ('Linux', 'Linux'), ('Android', 'Android'), ('iOS', 'iOS'), ('Cross-Platform', 'Cross-Platform')], default='Windows', max_length=50),
        ),
        migrations.AlterField(
            model_name='software',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='website_link',
            field=models.URLField(blank=True, help_text='Official website link.', null=True),
        ),
        migrations.AlterField(
            model_name='softwaredownloadpageversion',
            name='display_title',
            field=models.CharField(blank=True, help_text="A specific title for this download page version (e.g., 'Latest 2025 Release').", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='softwaredownloadpageversion',
            name='software',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_page_versions', to='software.software'),
        ),
        migrations.AlterField(
            model_name='softwaredownloadpageversion',
            name='version_number',
            field=models.CharField(help_text='e.g., 1.0, 2.5.1 (specific to this download page)', max_length=50),
        ),
        migrations.AlterField(
            model_name='softwareversion',
            name='download_link_url',
            field=models.URLField(blank=True, help_text='Direct download URL for this version (if primary).', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='softwareversion',
            name='is_current_version',
            field=models.BooleanField(default=False, help_text='Set as current version for this software.'),
        ),
        migrations.AlterField(
            model_name='softwareversion',
            name='version_number',
            field=models.CharField(help_text='e.g., 1.0, 2.5.1', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='downloadlink',
            unique_together={('version', 'name')},
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
