# Generated by Django 5.1.7 on 2025-06-26 04:28

import ckeditor_uploader.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0007_alter_downloadlink_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='downloadlink',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='software',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Software'},
        ),
        migrations.AlterModelOptions(
            name='softwaredownloadpageversion',
            options={'ordering': ['-release_date', '-version_number'], 'verbose_name': 'Software Download Page Version', 'verbose_name_plural': 'Software Download Page Versions'},
        ),
        migrations.AlterModelOptions(
            name='softwareversion',
            options={'ordering': ['-release_date', '-version_number']},
        ),
        migrations.RemoveField(
            model_name='softwaredownloadpageversion',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='softwareversion',
            name='additional_info',
        ),
        migrations.AddField(
            model_name='software',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='software',
            name='total_ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='softwaredownloadpageversion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='softwaredownloadpageversion',
            name='notes',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Specific notes or changes for this download page version.', null=True),
        ),
        migrations.AddField(
            model_name='softwaredownloadpageversion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='downloadlink',
            name='name',
            field=models.CharField(help_text="e.g., 'Direct Download', 'Mirror 1'", max_length=200),
        ),
        migrations.AlterField(
            model_name='downloadlink',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='downloadlink',
            name='url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='downloadpagespecificlink',
            name='name',
            field=models.CharField(help_text='Descriptive name for this specific download.', max_length=200),
        ),
        migrations.AlterField(
            model_name='downloadpagespecificlink',
            name='url',
            field=models.URLField(help_text='The URL for this specific download.', max_length=500),
        ),
        migrations.AlterField(
            model_name='software',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='file_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='homepage_description',
            field=models.TextField(blank=True, help_text='A short description for the homepage.', null=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='license_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='operating_system',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='website_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='softwaredownloadpageversion',
            name='display_title',
            field=models.CharField(blank=True, default='', help_text="Title for this download page version (e.g., 'v1.0 Installer').", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='softwaredownloadpageversion',
            name='version_number',
            field=models.CharField(help_text='Version number associated with this specific download page.', max_length=50),
        ),
        migrations.AlterField(
            model_name='softwareversion',
            name='download_link_url',
            field=models.URLField(blank=True, help_text='Direct download URL for this version (optional if using specific links).', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='softwareversion',
            name='is_current_version',
            field=models.BooleanField(default=False, help_text='Only one version should be marked as current per software.'),
        ),
        migrations.AlterField(
            model_name='softwareversion',
            name='version_number',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user who submitted the rating.', null=True)),
                ('score', models.IntegerField(help_text='Rating from 1 (lowest) to 5 (highest) stars.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='software.software')),
                ('user', models.ForeignKey(blank=True, help_text='The logged-in user who submitted the rating (optional for anonymous ratings).', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
                'unique_together': {('software', 'ip_address')},
            },
        ),
    ]
