# Generated by Django 5.1.7 on 2025-06-26 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0008_alter_downloadlink_options_alter_software_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='rating',
            name='ip_address',
        ),
    ]
