# Generated by Django 5.1.7 on 2025-07-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0009_alter_rating_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('name_fr', models.CharField(max_length=100, null=True)),
                ('name_es', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
