# Generated by Django 5.1.7 on 2025-07-03 18:03

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0010_mymodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='name_fr',
        ),
        migrations.AddField(
            model_name='software',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='description_es',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='description_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='name_en',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='software',
            name='name_es',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='software',
            name='name_fr',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
