# Generated by Django 5.1.7 on 2025-07-05 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0011_remove_mymodel_name_en_remove_mymodel_name_es_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='software',
            name='description_es',
        ),
        migrations.RemoveField(
            model_name='software',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='software',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='software',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='software',
            name='name_fr',
        ),
        migrations.AddField(
            model_name='mymodel',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='name_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='name_fr',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
