# Generated by Django 4.2.22 on 2025-07-05 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0013_remove_mymodel_name_en_remove_mymodel_name_es_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_fr',
        ),
    ]
