# Generated by Django 4.2.22 on 2025-07-06 13:31

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0014_delete_mymodel_remove_category_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='description_ar',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='description_de',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='name_ar',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='software',
            name='name_de',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
