# Generated by Django 4.2.22 on 2025-07-07 11:54

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0015_software_description_ar_software_description_de_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_ar',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_de',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_es',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='software',
            name='homepage_description_ar',
            field=models.TextField(blank=True, help_text='A short description for the homepage.', null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='homepage_description_de',
            field=models.TextField(blank=True, help_text='A short description for the homepage.', null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='homepage_description_en',
            field=models.TextField(blank=True, help_text='A short description for the homepage.', null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='homepage_description_es',
            field=models.TextField(blank=True, help_text='A short description for the homepage.', null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='homepage_description_fr',
            field=models.TextField(blank=True, help_text='A short description for the homepage.', null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='requirements_ar',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='System requirements for the software.', null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='requirements_de',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='System requirements for the software.', null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='requirements_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='System requirements for the software.', null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='requirements_es',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='System requirements for the software.', null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='requirements_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='System requirements for the software.', null=True),
        ),
    ]
