# Generated by Django 5.1.7 on 2025-07-10 13:19

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0016_category_name_ar_category_name_de_category_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_zh_hans',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='software',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='description_zh_hans',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='homepage_description_ru',
            field=models.TextField(blank=True, help_text='A short description for the homepage.', null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='homepage_description_zh_hans',
            field=models.TextField(blank=True, help_text='A short description for the homepage.', null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='software',
            name='name_zh_hans',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='software',
            name='requirements_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='System requirements for the software.', null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='requirements_zh_hans',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='System requirements for the software.', null=True),
        ),
    ]
