# Generated by Django 4.2.14 on 2025-07-31 19:10
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0018_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Whether this software should be publicly visible.'),
        ),
    ]
