# Generated by Django 5.1.7 on 2025-08-05 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0021_category_is_published_category_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Optional. Description for SEO.', null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Optional. Title for SEO, defaults to category name.', max_length=255, null=True, verbose_name='Meta Title'),
        ),
    ]
