# Generated by Django 5.1.7 on 2025-08-05 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0022_category_meta_description_category_meta_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Description [ar]'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='Description [de]'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description [en]'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='Description [es]'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Description [fr]'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Description [ru]'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_zh_hans',
            field=models.TextField(blank=True, null=True, verbose_name='Description [zh-hans]'),
        ),
    ]
