# Generated by Django 5.1.7 on 2025-08-05 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0023_category_description_ar_category_description_de_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='meta_title',
        ),
    ]
