# Generated by Django 5.1.7 on 2025-08-05 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0024_remove_category_meta_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='meta_description_ar',
            field=models.TextField(blank=True, help_text='Optional. Description for SEO.', null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description_de',
            field=models.TextField(blank=True, help_text='Optional. Description for SEO.', null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description_en',
            field=models.TextField(blank=True, help_text='Optional. Description for SEO.', null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description_es',
            field=models.TextField(blank=True, help_text='Optional. Description for SEO.', null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description_fr',
            field=models.TextField(blank=True, help_text='Optional. Description for SEO.', null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description_ru',
            field=models.TextField(blank=True, help_text='Optional. Description for SEO.', null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description_zh_hans',
            field=models.TextField(blank=True, help_text='Optional. Description for SEO.', null=True, verbose_name='Meta Description'),
        ),
    ]
