# Generated by Django 5.1.7 on 2025-08-06 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0025_category_meta_description_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Optional. Title for SEO, defaults to category name.', max_length=255, null=True, verbose_name='Meta Title'),
        ),
    ]
